name: Run JMeter Tests hohohehe

on:
  # auto trigger upon push to master branch
  #push:
  #  branches:
  #    - master

jobs:
  performance-test:

    runs-on: ubuntu-latest

    steps:

      # 1. Download repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Java (required by JMeter)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Download JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      # 4. Run test plan
      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t github_jmeter.jmx \
            -l results.jtl \
            -j jmeter.log \
            -e -o report

      # 5. Save artifacts
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            results.jtl 
            jmeter.log 
            report/