# to trigger Jmeter
# output Jmeter xml instead of jtl->then extract required info from jmeter xml log -> use program to convert it to html -> print pytest result on UI

name: Run JMeter & pytest Tests workflow

  # auto trigger upon push to master branch, i comment out to disable the auto trigger
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # First job: execute performance tests using JMeter
  test-using-jmeter:
    runs-on: ubuntu-latest

    # Permissions required for deploying reports to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # GitHub Pages deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Download repository source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Java runtime required by JMeter
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Download and extract Apache JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      # 4. Execute JMeter test plan in non-GUI mode
      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t postman.jmx \
            -l results.xml \
            -j jmeter.log \
            -Jlog_level.jmeter=INFO \
            -Jjmeter.save.saveservice.output_format=xml \
            -Jjmeter.save.saveservice.response_data=true \
            -Jjmeter.save.saveservice.samplerData=true

      # 5a. Convert XML test results into an HTML report  (using python)
#      - name: Convert JMeter XML to HTML
#        run: |
#          python jmeter_xml_to_html.py results.xml results_html.html

      # 5b. Convert XML test results into an HTML report  (using powershell)
      - name: Convert XML to HTML
        shell: pwsh
        run: |
          ./jmeter_xml_to_html.ps1 results.xml results_html.html

      # 6. Store test artifacts for later download manually
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            results.xml   
            jmeter.log
            results_html.html
            
      # Prepare files that will be published to GitHub Pages
      - name: Prepare Pages content
        run: |
          mkdir pages
          cp results_html.html pages/index.html

      # Configure GitHub Pages deployment
      # Ensure GitHub Pages is enabled:
      # Repository → Settings → Pages → Build and deployment → Source: GitHub Actions
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload website files as a special Pages artifact
        # you must store this, so that github can use the html here to publish on UI
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

      # Publish the HTML report to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



