name: Run my Pytest hahahehe

#on:
  #### auto trigger upon push to master branch
  #push:
  #  branches:
  #    - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Generate BOTH html + xml
      - name: Run pytest
        run: |
          pytest -v --color=yes \
            --html=report.html \
            --junitxml=report.xml

      # Upload HTML file for download
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

      # Parse XML and show test summary in GitHub UI
      - name: Test Reporter
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Pytest Results
          path: report.xml
          reporter: java-junit
