# to trigger Jmeter jobs & pytest jobs in one workflow
# best practise is to run them in separate job , or even workflow(YAML). depends on ur need
name: Run JMeter & pytest Tests

on:
  #auto trigger upon push to master branch
  push:
    branches:
      - master

jobs:
  # first job ,jmeter
  performance-test-jmeter:
    runs-on: ubuntu-latest

    steps:

      # 1. Download repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Java (required by JMeter)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Download JMeter
      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      # 4. Run test plan
      - name: Run JMeter Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t github_jmeter.jmx \
            -l results.jtl \
            -j jmeter.log \
            -e -o report

      # 5. Save artifacts
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            results.jtl 
            jmeter.log 
            report/

  # 2nd job, using pytest
  test-using-pytest:
    needs: performance-test-jmeter  #by default, all jobs run concurrently. use needs to set dependency
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Generate BOTH html + xml
      - name: Run pytest
        run: |
          pytest -v --color=yes \
            --html=report.html \
            --junitxml=report.xml

      # Upload HTML file for download
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

      # Parse XML and show test summary in GitHub UI
      - name: Test Reporter
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
          name: Pytest Results
          path: report.xml
          reporter: java-junit
